#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com  
#=================================================

name:  ax18_test

on:
  #手动编译
  workflow_dispatch:
    inputs:
      iCONFIG:
        description: '配置文件名：'
        required: false
        type: string
        default: 'ax18.txt'
      iDIY:
        description: 'DIY脚本：'
        required: false
        type: string
        default: 'diyconfig_ax18.sh'
      iUpdate_bin:
        description: '是否上传Bin：'
        required: false
        type: boolean
        default: true
      iRelease_FIRMWARE:
        description: '是否发布firmware：'
        required: false
        type: boolean
        default: false

#环境变量配置
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: ${{inputs.iCONFIG}}
  DIYCONFIG: ${{inputs.iDIY}}
  DIY_FEEDS: diy_feeds.sh  # 主要用于更新Feeds
  GENERAL_CONFIG: GENERAL.txt   # 通用配置
  DIYPackages: Packages.sh
  CLASH_KERNEL: amd64
  CACHE_TOOLCHAIN: true
  FREE_UP_DISK: true
  UPLOAD_BIN_DIR: ${{inputs.iUpdate_bin}}
  UPLOAD_FIRMWARE: false
  FIRMWARE_RELEASE: ${{inputs.iRelease_FIRMWARE}}
  FIRMWARE_TAG: ax18
  TZ: Asia/Shanghai
  CONFIGS_DIR: Config
  SCRIPTS_DIR: Scripts
  
#CI权限
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:

    - name: Check Server Performance (检查服务器性能)
      run: |
        echo "警告⚠"
        echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
        echo -e "已知CPU型号（降序）：7763，8370C，8272CL，8171M，E5-2673 \n"
        echo "--------------------------CPU信息--------------------------"
        echo "CPU物理数量：$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo -e "CPU核心信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo "--------------------------内存信息--------------------------"
        echo "已安装内存详细信息："
        echo -e "$(sudo lshw -short -C memory | grep GiB) \n"
        echo "--------------------------硬盘信息--------------------------"
        echo "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT
        echo "【LinInfo】env.FIRMWARE_RELEASE: ${{ env.FIRMWARE_RELEASE }}"
        echo "【LinInfo】env.FIRMWARE_RELEASE: ${{ env.UPLOAD_BIN_DIR }}"
        echo "【LinInfo】env.FIRMWARE_RELEASE: ${{ env.UPLOAD_FIRMWARE }}"
        echo "【LinInfo】env.FIRMWARE_RELEASE: ${{ inputs.iUpdate_bin }}"
        echo "【LinInfo】env.FIRMWARE_RELEASE: ${{ inputs.iRelease_FIRMWARE }}"

    - name: config git (修改git下载缓冲大小1)
      if: env.FREE_UP_DISK == true
      run: |
        git config --global http.postBuffer 524288000
        git config --global http.lowSpeedLimit 0
        git config --global http.lowSpeedTime 999999
        echo "【LinInfo】{} == true"

    - name: config git (修改git下载缓冲大小2)
      if: env.FREE_UP_DISK == 'true'
      run: |
        echo "【LinInfo】{} == 'true'"

    - name: config git (修改git下载缓冲大小3)
      if: env.UPLOAD_FIRMWARE == false
      run: |
        echo "【LinInfo】{} == 'true'"

