#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com  
#=================================================

name:  ax18_test

on:
  #手动编译
  workflow_dispatch:
    inputs:
      iCONFIG:
        description: '配置文件名：'
        required: false
        type: string
        default: 'ax18.txt'
      iDIY:
        description: 'DIY脚本：'
        required: false
        type: string
        default: 'diyconfig_ax18.sh'
      iUpdate_bin:
        description: '是否上传Bin：'
        required: false
        type: boolean
        default: true
      iRelease_FIRMWARE:
        description: '是否发布firmware：'
        required: false
        type: boolean
        default: false

#环境变量配置
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: ${{inputs.iCONFIG}}
  DIYCONFIG: ${{inputs.iDIY}}
  DIY_FEEDS: diy_feeds.sh  # 主要用于更新Feeds
  GENERAL_CONFIG: GENERAL.txt   # 通用配置
  DIYPackages: Packages.sh
  CLASH_KERNEL: amd64
  CACHE_TOOLCHAIN: true
  FREE_UP_DISK: true
  UPLOAD_BIN_DIR: ${{inputs.iUpdate_bin}}
  UPLOAD_FIRMWARE: true
  FIRMWARE_RELEASE: ${{inputs.iRelease_FIRMWARE}}
  FIRMWARE_TAG: ax18
  TZ: Asia/Shanghai
  CONFIGS_DIR: Config
  SCRIPTS_DIR: Scripts
  
#CI权限
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:

    - name: Check Server Performance (检查服务器性能)
      run: |
        echo "警告⚠"
        echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
        echo -e "已知CPU型号（降序）：7763，8370C，8272CL，8171M，E5-2673 \n"
        echo "--------------------------CPU信息--------------------------"
        echo "CPU物理数量：$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo -e "CPU核心信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo "--------------------------内存信息--------------------------"
        echo "已安装内存详细信息："
        echo -e "$(sudo lshw -short -C memory | grep GiB) \n"
        echo "--------------------------硬盘信息--------------------------"
        echo "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT
        echo "【LinInfo】env.FIRMWARE_RELEASE: ${{ env.FIRMWARE_RELEASE }}"
        echo "【LinInfo】env.FIRMWARE_RELEASE: ${{ env.UPLOAD_BIN_DIR }}"
        echo "【LinInfo】env.FIRMWARE_RELEASE: ${{ env.UPLOAD_FIRMWARE }}"
        echo "【LinInfo】env.FIRMWARE_RELEASE: ${{ inputs.iUpdate_bin }}"
        echo "【LinInfo】env.FIRMWARE_RELEASE: ${{ inputs.iRelease_FIRMWARE }}"

    - name: Free Disk Space
      uses: endersonmenezes/free-disk-space@main
      if: ${{ env.FREE_UP_DISK }} == true
      with:
        remove_android: true
        remove_dotnet: true
        remove_haskell: true
        remove_tool_cache: true
        remove_swap: true
        remove_packages: "android* azure* clang* dotnet* firefox* ghc* golang* google* libclang* libgl1* lld* llvm* microsoft* mongodb* mono* mysql* nodejs* openjdk* php* postgresql* powershell* snap* temurin* yarn* zulu*"
        remove_packages_one_command: true
        remove_folders: "/etc/apt/sources.list.d* /etc/mono* /etc/mysql* /usr/include/linux/android* /usr/lib/llvm* /usr/lib/mono* /usr/local/lib/android* /usr/local/lib/node_modules* /usr/local/share/chromium* /usr/local/share/powershell* /usr/local/share/vcpkg/ports/azure* /usr/local/share/vcpkg/ports/google* /usr/local/share/vcpkg/ports/libpq/android* /usr/local/share/vcpkg/ports/llvm* /usr/local/share/vcpkg/ports/mysql* /usr/local/share/vcpkg/ports/snap* /usr/share/azure* /usr/share/dotnet* /usr/share/glade* /usr/share/miniconda* /usr/share/php* /usr/share/swift /var/lib/mysql* /var/log/azure*"
        testing: false
