#CI项目
name: CUSTOM-APK

#CI计划
on:
  workflow_dispatch:
    inputs:
      WHAT_MY_SAY:
        description: '编译说明'
        required: false
        type: string
        default: ''

#CI权限
permissions: write-all

#CI任务
jobs:
  ipq60xx_nowifi_fw3_apk:
    name: lean-IPQ60XX-NOWIFI-fw3-apk
    uses: ./.github/workflows/DEFAULT.yml
    with:
      WRT_DEVICE: IPQ60XX-NOWIFI
      WRT_FIREWALL: fw3
      WRT_OVERLAYS: apk
      WRT_DIY_SETTING: diy_config.sh
      WRT_DIYPackages: Packages.sh
      WRT_DEFAULT_LANIP: 192.168.0.1
      WRT_RELEASE_FIRMWARE: false
      WHAT_MY_SAY: ${{ inputs.WHAT_MY_SAY }}
      WRT_SOURCE_FLAVOR: lean
    secrets: inherit

  ipq60xx_nowifi_fw3_frps_apk:
    name: lean-IPQ60XX-NOWIFI-fw3-frps-apk
    uses: ./.github/workflows/DEFAULT.yml
    with:
      WRT_DEVICE: IPQ60XX-NOWIFI
      WRT_FIREWALL: fw3
      WRT_OVERLAYS: frps,apk
      WRT_DIY_SETTING: diy_config.sh
      WRT_DIYPackages: Packages.sh
      WRT_DEFAULT_LANIP: 192.168.0.1
      WRT_RELEASE_FIRMWARE: false
      WHAT_MY_SAY: ${{ inputs.WHAT_MY_SAY }}
      WRT_SOURCE_FLAVOR: lean
    secrets: inherit

  mt6000_wifi_fw3_apk:
    name: lean-MT6000-WIFI-fw3-apk
    uses: ./.github/workflows/DEFAULT.yml
    with:
      WRT_DEVICE: MT6000-WIFI
      WRT_FIREWALL: fw3
      WRT_OVERLAYS: apk
      WRT_DIY_SETTING: diy_config.sh
      WRT_DIYPackages: Packages.sh
      WRT_DEFAULT_LANIP: 192.168.0.1
      WRT_RELEASE_FIRMWARE: false
      WHAT_MY_SAY: ${{ inputs.WHAT_MY_SAY }}
      WRT_SOURCE_FLAVOR: lean
    secrets: inherit

  mt6000_wifi_fw4_vikingyfy_apk:
    name: VIKINGYFY-MT6000-WIFI-fw4-apk
    uses: ./.github/workflows/DEFAULT.yml
    with:
      WRT_DEVICE: MT6000-WIFI
      WRT_FIREWALL: fw4
      WRT_OVERLAYS: apk
      WRT_DIY_SETTING: diy_config.sh
      WRT_DIYPackages: Packages.sh
      WRT_DEFAULT_LANIP: 192.168.0.1
      WRT_RELEASE_FIRMWARE: false
      WHAT_MY_SAY: ${{ inputs.WHAT_MY_SAY }}
      WRT_SOURCE_FLAVOR: VIKINGYFY
    secrets: inherit
