#CI项目
name: CUSTOM

#CI计划
on:
  #自动清理：每天早上5点
  # schedule:
  #  - cron: 0 21 * * *
  #自动编译：当Auto-Clean运行完成后
  #workflow_run:
  #  workflows: ["Auto-Clean"]
  #  types:
  #   - completed
  #手动编译
  workflow_dispatch:
    inputs:
      iWRT_CONFIG:
        description: '配置文件：'
        required: true
        type: string
        default: 'IPQ60XX-NOWIFI.txt'
      iWRT_DIY_SETTING:
        description: 'DIY脚本：'
        required: false
        type: string
        default: 'IPQ60XX.sh'
      iWRT_DIYPackages:
        description: 'DIY包配置：'
        required: false
        type: string
        default: 'Packages.sh'
      iWRT_DEFAULT_LANIP:
        description: '配置LAN-IP'
        required: false
        type: string
        default: '192.168.0.1'
      iWRT_RELEASE_FIRMWARE:
        description: '发布firmware'
        required: false
        type: boolean
        default: true
      iWHAT_MY_SAY:
        description: '编译说明'
        required: false
        type: string
        default: ''
      iTOKEN_DINGDING:
        description: '钉钉TOKEN'
        required: false
        type: string
        default: ''
      iWRT_REPO_Commit_Hash:
        description: '历史版本HASH'
        required: false
        type: string
        default: ''
      # iWRT_GENERAL_CONFIG:
      #   description: '通用配置文件'
      #   required: true
      #   type: string
      #   default: 'GENERAL.txt'


#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{matrix.TARGET}}
    strategy:
      fail-fast: false
      #max-parallel: 2
      matrix:
        TARGET: [IPQ60XX-NOWIFI]
        SOURCE: ['https://github.com/coolsnowwolf/lede']
        BRANCH: [master]

    #调用公用编译核心ALL-CORE.yml
    uses: ./.github/workflows/CORE-ALL.yml
    with:
      # 源码
      WRT_REPO_URL: ${{ matrix.SOURCE }}
      # 编译分支
      WRT_REPO_BRANCH: ${{ matrix.BRANCH }}
      # 编译指定版本
      WRT_REPO_Commit_Hash: ${{ inputs.iWRT_REPO_Commit_Hash }}
      # DIY配置文件
      WRT_CONFIG: ${{ inputs.iWRT_CONFIG }}
      # 通用配置
      WRT_GENERAL_CONFIG: GENERAL.txt
      # DIY脚本
      WRT_DIY_SETTING: ${{ inputs.iWRT_DIY_SETTING }}
      # DIY包配置
      WRT_DIYPackages: ${{ inputs.iWRT_DIYPackages }}
      # FEED配置
      WRT_DIY_FEEDS: diy_feeds.sh
      # 是否发布
      WRT_RELEASE_FIRMWARE: ${{ inputs.iWRT_RELEASE_FIRMWARE }} # 发布固件
      # 默认LAN-IP
      WRT_DEFAULT_LANIP: ${{ inputs.iWRT_DEFAULT_LANIP }}
      # 钉钉TOKEN，用于推送下载文件
      WRT_TOKEN_DINGDING: ''
      # 编译说明
      WRT_MINE_SAY: ${{ inputs.iWHAT_MY_SAY }}
      
