#CI项目
name: DEFAULT

on:
  #手动编译
  workflow_dispatch:
    inputs:
      WRT_CONFIG:
        description: '配置文件'
        required: true
        type: choice
        options:
          - IPQ60XX-NOWIFI.txt
          - IPQ60XX-NOWIFI_FRPS.txt
          - MT6000.txt
        default: 'IPQ60XX-NOWIFI.txt'
      WRT_DIY_SETTING:
        description: 'diy_setting脚本'
        required: false
        type: string
        default: 'diy_config.sh'
      WRT_DIYPackages:
        description: 'DIY包配置'
        required: false
        type: string
        default: 'Packages.sh'
      WRT_DEFAULT_LANIP:
        description: '默认LAN-IP'
        required: false
        type: string
        default: '192.168.0.1'
      WRT_RELEASE_FIRMWARE:
        description: '发布firmware'
        required: false
        type: boolean
        default: true
      WHAT_MY_SAY:
        description: '编译说明'
        required: false
        type: string
        default: ''
      WRT_REPO_URL:
        description: '源码'
        required: true
        type: string
        default: 'https://github.com/coolsnowwolf/lede'
      WRT_REPO_Commit_Hash:
        description: '历史版本HASH'
        required: false
        type: string
        default: ''

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{inputs.WRT_CONFIG}}
    strategy:
      fail-fast: false
      #max-parallel: 2
      matrix:
        TARGET: [IPQ60XX-NOWIFI]
        SOURCE: ['https://github.com/coolsnowwolf/lede']
        BRANCH: [master]

    #调用公用编译核心ALL-CORE.yml
    uses: ./.github/workflows/CORE-ALL.yml
    with:
      # 源码
      WRT_REPO_URL: ${{ inputs.WRT_REPO_URL || 'https://github.com/coolsnowwolf/lede' }}
      # 编译分支
      WRT_REPO_BRANCH: ${{ matrix.BRANCH || 'master' }}
      # 编译指定版本
      WRT_REPO_Commit_Hash: ${{ inputs.WRT_REPO_Commit_Hash }}
      # DIY配置文件
      WRT_CONFIG: ${{ inputs.WRT_CONFIG }}
      # 通用配置
      WRT_GENERAL_CONFIG: GENERAL.txt
      # DIY脚本
      WRT_DIY_SETTING: ${{ inputs.WRT_DIY_SETTING }}
      # DIY包配置
      WRT_DIYPackages: ${{ inputs.WRT_DIYPackages }}
      # FEED配置
      WRT_DIY_FEEDS: diy_feeds.sh
      # 是否发布
      WRT_RELEASE_FIRMWARE: ${{ inputs.WRT_RELEASE_FIRMWARE }} # 发布固件
      # 默认LAN-IP
      WRT_DEFAULT_LANIP: ${{ inputs.WRT_DEFAULT_LANIP }}
      # 钉钉TOKEN，用于推送下载文件
      WRT_TOKEN_DINGDING: ${{inputs.iTOKEN_DINGDING}}
      # 编译说明
      WRT_MINE_SAY: ${{ inputs.WHAT_MY_SAY }}
      # 是否使用APK包管理器
      WRT_USE_APK: false
    secrets:
      # 钉钉TOKEN
      DINGDING_TOKEN: ${{ secrets.DINGDING_TOKEN }}
      

