#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
#=================================================

name:  IPQ60XX-NOWIFI-FW4

on:
  #手动编译
  workflow_dispatch:
    inputs:
      iCONFIG:
        description: '配置文件：'
        required: true
        type: string
        default: 'IPQ60XX-NOWIFI-FW4.txt'
      iDIY:
        description: 'DIY脚本：'
        required: false
        type: string
        default: 'diyconfig_ax18.sh'
      iGENERAL:
        description: '通用配置文件'
        required: true
        default: 'GENERAL.txt'
        type: choice
        options:
          - 'GENERAL.txt'
          - 'GENERAL_custom.txt'
      i_lan_ip:
        description: '配置LAN-IP'
        required: false
        type: string
        default: '192.168.0.1'
      iUpdate_bin:
        description: '将固件上传到Artifact'
        required: false
        type: boolean
        default: true
      iRelease_FIRMWARE:
        description: '发布firmware'
        required: false
        type: boolean
        default: true
      iReset_password:
        description: '重置root密码'
        required: false
        type: boolean
        default: false
      iResize_space:
        description: '云编译磁盘扩容(编译大文件用)'
        required: false
        type: boolean
        default: false
      iRepoURL_commit_hash:
        description: '历史版本HASH'
        required: false
        type: string
        default: ''

#环境变量配置
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  REPO_Commit_Hash: ${{inputs.iRepoURL_commit_hash}}
  CONFIG_FILE: ${{inputs.iCONFIG}}                # 配置文件
  DIY_SETTING: ${{inputs.iDIY}}                   # 自定义配置
  DIY_FEEDS: diy_feeds.sh                         # 主要用于更新Feeds
  GENERAL_CONFIG: ${{inputs.iGENERAL}}            # 通用配置
  DIYPackages: Packages.sh                        # 自定义包配置
  CLASH_KERNEL: amd64
  CACHE_TOOLCHAIN: true
  FREE_UP_DISK: true
  UPLOAD_FIRMWARE_DIR: ${{inputs.iUpdate_bin}}
  UPLOAD_BIN_DIR: false                           # 是否上传编译后的bin目录，因整理编译后的文件设置了UPLOAD_FIRMWARE_DIR，所以不上传整个bin目录
  FIRMWARE_RELEASE: ${{inputs.iRelease_FIRMWARE}} # 发布固件
  IS_RESET_PASSWORD: ${{inputs.iReset_password}}  # 是否把密码重置为空
  IS_RESIZE_SPACE: ${{inputs.iResize_space}}      # 是否扩容空间，一般编译内容不多，可以不扩容，减少资源浪费
  TZ: Asia/Shanghai
  CONFIGS_DIR: Config                             # 自定义配置文件夹
  SCRIPTS_DIR: Scripts                            # 脚本文件夹
  DEFAULT_LANIP: ${{inputs.i_lan_ip}}             # 默认lanIP
  
#CI权限
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:

    - name: Send dingding notify
      uses: zcong1993/actions-ding@master
      with:
        dingToken: "c6952c2946adb0b97d741623975c8f4cc41cffd0b0441f6bcbb164c86bde1338"
        body: |
          {
            "msgtype": "text",
            "text": {
                "content": "路由器推送测试"
             }
          }
